<?php
defined('ABSPATH') || exit;
require_once __DIR__ . '/product-navigation.php';
require_once __DIR__ . '/site-layout.php';
function bcst_t($text){return function_exists('bcst_text')?bcst_text($text):$text;}
function bcst_setting($key,$default=''){$s=get_option('bcst_settings',array());return !empty($s[$key])?$s[$key]:$default;}
function bcst_page_url($slug){$p=get_page_by_path($slug);if(!$p)return home_url('/'.$slug.'/');$id=$p->ID;if(function_exists('pll_get_post'))$id=pll_get_post($id)?:$id;return get_permalink($id);}
function bcst_home(){return function_exists('pll_home_url')?pll_home_url():home_url('/');}
add_action('after_setup_theme',function(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('custom-logo');add_theme_support('responsive-embeds');add_theme_support('html5',array('search-form','gallery','caption','style','script'));register_nav_menus(array('primary'=>'主导航'));});
add_action('wp_enqueue_scripts',function(){wp_enqueue_style('bcst-industrial',get_stylesheet_uri(),array(),'1.0.0');wp_enqueue_script('bcst-site',get_template_directory_uri().'/site.js',array(),'1.0.0',true);});
function bcst_default_menu(){echo '<ul class="menu">';foreach(array('home'=>'Home','products'=>'Products','industries'=>'Industries','about'=>'About Us','insights'=>'Insights','contact'=>'Contact Us') as $slug=>$label){$url=$slug==='home'?bcst_home():($slug==='products'?get_post_type_archive_link('bcst_product'):bcst_page_url($slug));echo '<li'.($slug==='products'?' class="bcst-product-nav"':'').'><a href="'.esc_url($url?:home_url('/')).'">'.esc_html(bcst_t($label)).'</a>';if($slug==='products')echo bcst_product_dropdown();echo '</li>';}echo '</ul>';}
function bcst_symbol(){echo '<svg viewBox="0 0 200 200" fill="none" stroke="currentColor" stroke-width="5" aria-hidden="true"><path d="M25 105h45l30 25 30-25h45v50h-45l-30-25-30 25H25zM100 125V65M65 65h70V35H65zM100 35V20M75 20h50"/><circle cx="100" cy="130" r="16"/><path d="M35 115v30m130-30v30M75 45h50"/></svg>';}
function bcst_card(){ ?><article class="card"><a href="<?php the_permalink(); ?>"><?php if(has_post_thumbnail())the_post_thumbnail('medium_large');else{echo '<div class="placeholder">';bcst_symbol();echo '</div>';} ?><h3><?php the_title(); ?></h3></a><p><?php echo esc_html(wp_trim_words(get_the_excerpt(),22)); ?></p><a href="<?php the_permalink(); ?>"><?php echo esc_html(bcst_t('View details')); ?> &rarr;</a></article><?php }
add_action('admin_init',function(){if(!function_exists('pll_register_string'))return;foreach(array('Home','Products','Industries','About Us','Insights','Contact Us','Resources','View details','Browse products','Request a quotation','Product specifications','Related products','Downloads','Frequently asked questions','Search','No items found.','Name','Email','Company','Country','Phone / WhatsApp','Requirements','I agree to be contacted about this inquiry.','Privacy policy','Send inquiry','Thank you. Your inquiry has been saved.','Inquiry received','Fluid measurement & control','Find the right equipment for your process','Explore our product range and send your operating requirements to discuss a suitable specification.','Tell us about your application','Share the medium, pressure, temperature and connection size with our team.','Latest insights','Product categories','Model','Back to home','Page not found','Product information','Technical resources') as $text)pll_register_string($text,$text,'BCST');foreach(array('headline','intro') as $key){$v=bcst_setting($key);if($v)pll_register_string('bcst_'.$key,$v,'BCST');}});
// Respect SEO plugin ownership; WordPress supplies canonical URLs and XML sitemaps.
add_action('wp_head',function(){if(defined('WPSEO_VERSION')||defined('RANK_MATH_VERSION')||defined('AIOSEO_VERSION'))return;if(is_singular()){$description=wp_strip_all_tags(get_the_excerpt());if($description)echo '<meta name="description" content="'.esc_attr(wp_trim_words($description,30)).'">'."\n";}},20);
add_action('admin_notices',function(){if(!function_exists('bcst_register')&&current_user_can('activate_plugins'))echo '<div class="notice notice-warning"><p>请先启用 BCST Industrial Core 插件，以使用产品、分类和询盘功能。</p></div>';});
